#https://docs.travis-ci.com/user/languages/python/

# language and version
language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage

# command to run tests
script:
#  - python3 -m pytest mutagenesis_visualization
  - coverage run -m pytest mutagenesis_visualization

after_success:
  - bash <(curl -s https://codecov.io/bash)
